
var main_trials = [
  {
    "item_id": 23,
    "item_type": "critical",
    "item_name": "paper-plane-kite",
    "det_target": "das",
    "det_competitor": "der",
    "question": "Ist das ein Bild von einem Papierflieger?",
    "question_file": "q_r_papierflieger.wav",
    "answer_file": "r_t_papierflieger.wav",
    "complete_answer": "Das ist tatsächlich ein Bild von einem Papierflieger.",
    "expected_response": "Papierflieger",
    "target": "Papierflieger",
    "competitor": "Drachen",
    "condition": "reliable",
    "DP": "indeed",
    "picture_target": "paperairplane.jpg",
    "picture_competitor": "kite.jpg"
  },
  {
    "item_id": 152,
    "item_type": "critical",
    "item_name": "snow-shovel-rake",
    "det_target": "die",
    "det_competitor": "die",
    "question": "Ist das ein Bild von einer Schneeschippe?",
    "question_file": "q_r_schneeschippe.wav",
    "answer_file": "r_e_harke.wav",
    "complete_answer": "Das ist eigentlich ein Bild von einer Harke.",
    "expected_response": "Harke",
    "target": "Schneeschippe",
    "competitor": "Harke",
    "condition": "reliable",
    "DP": "actually",
    "picture_target": "snowshovel.jpg",
    "picture_competitor": "leafrake.jpg"
  },
  {
    "item_id": 231,
    "item_type": "filler",
    "item_name": "swiss-army-knife",
    "det_target": "NA",
    "det_competitor": "NA",
    "question": "Ist das ein Messer?",
    "question_file": "q_f_taschenmesser.wav",
    "answer_file": "f_schweizertaschenmesser.wav",
    "complete_answer": "Ja, das ist ein schweizer Taschenmesser.",
    "expected_response": "swissarmyknife01a.jpg",
    "target": "NA",
    "competitor": "NA",
    "condition": "filler",
    "DP": "NA",
    "picture_target": "swissarmyknife01a.jpg",
    "picture_competitor": "litterbox.jpg"
  },
  {
    "item_id": 230,
    "item_type": "filler",
    "item_name": "honeycomb",
    "det_target": "NA",
    "det_competitor": "NA",
    "question": "Ist das gelbe Ding, das, wovon wir Honig bekommen?",
    "question_file": "q_f_bienenwabe.wav",
    "answer_file": "f_bienenwabe.wav",
    "complete_answer": "Ja, das ist eine Bienenwabe.",
    "expected_response": "honeycomb.jpg",
    "target": "NA",
    "competitor": "NA",
    "condition": "filler",
    "DP": "NA",
    "picture_target": "honeycomb.jpg",
    "picture_competitor": "windshieldwiper02.jpg"
  }
];
